package:
  format-version: "1.0.0"
  name: "reference_apps_pic32cz"
  type: "application"
  status: "production"
  required: false
  version: "1.1.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.23.0"
    - name: "core"
      type: "package"
      version: "v3.15.5"
    - name: "FreeRTOS-Kernel"
      type: "package"
      version: "V11.2.0"
    - name: "cryptoauthlib"
      type: "package"
      version: "v3.7.9"
    - name: "wireless_wifi"
      type: "package"
      version: "v3.12.1"
    - name: "wireless_system_pic32mzw1_wfi32e01"
      type: "package"
      version: "v3.9.1"
    - name: "wolfssl"
      type: "package"
      version: "v5.7.0"
    - name: "net"
      type: "package"
      version: "v3.14.4"
    - name: "crypto"
      type: "package"
      version: "v3.8.2"
    - name: "wireless_rnbd"
      type: "package"
      version: "v2.0.6"
    - name: "wireless_ble"
      type: "package"
      version: "v1.5.0"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "v1.6.0"
    - name: "gfx"
      type: "package"
      version: "v3.16.3"      
    - name: "paho.mqtt.embedded-c"
      type: "package"
      version: "v1.2.3"        