package:
  format-version: "1.0.0"
  name: "reference_apps_pic32cz"
  type: "application"
  status: "production"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.20.0-E1"
    - name: "core"
      type: "package"
      version: "v3.14.1"
    - name: "FreeRTOS-Kernel"
      type: "package"
      version: "v11.1.0"
    - name: "cryptoauthlib"
      type: "package"
      version: "v3.7.6"
    - name: "wireless_wifi"
      type: "package"
      version: "v3.11.1"
    - name: "wireless_system_pic32mzw1_wfi32e01"
      type: "package"
      version: "v3.9.1"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "net"
      type: "package"
      version: "v3.12.3"
    - name: "crypto"
      type: "package"
      version: "v3.8.2"
    - name: "wireless_rnbd"
      type: "package"
      version: "v2.0.3"
    - name: "wireless_ble"
      type: "package"
      version: "v1.3.0"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "v1.4.0"